# Generated by Django 5.1.5 on 2025-01-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_lot', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=100)),
                ('item_number', models.CharField(max_length=100)),
                ('item_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_of_measure_code', models.CharField(blank=True, max_length=50, null=True)),
                ('box', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('shipment_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('carbon_qty', models.FloatField(blank=True, null=True)),
                ('lot_carbon', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_order_number', models.CharField(max_length=100)),
                ('sales_order_line_number', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_order_number', models.CharField(max_length=100)),
                ('customer_order_line_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_amount_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('project_code', models.CharField(blank=True, max_length=100, null=True)),
                ('hs_code', models.CharField(blank=True, max_length=100, null=True)),
                ('net_weight_kg', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('lu_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
