# Generated by Django 5.1.5 on 2025-01-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('incoterms', models.CharField(max_length=50)),
                ('operation', models.CharField(choices=[('import', 'Import'), ('inward_processing', 'Inward Processing')], max_length=50)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('gross_weight', models.FloatField()),
                ('is_dangerous', models.BooleanField(default=False)),
                ('is_stackable', models.BooleanField(default=True)),
                ('pickup_address', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
