# Generated by Django 5.1.5 on 2025-01-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_alter_import_incoterms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='incoterms',
            field=models.CharField(choices=[('NoN', 'Non'), ('EXW', 'EXW – Ex Works'), ('FCA', 'FCA – Free Carrier'), ('CPT', 'CPT – Carriage Paid To'), ('CIP', 'CIP – Carriage and Insurance Paid To'), ('DAP', 'DAP – Delivered at Place'), ('DPU', 'DPU – Delivered at Place Unloaded'), ('DDP', 'DDP – Delivered Duty Paid')], max_length=3),
        ),
    ]
