# Generated by Django 5.1.5 on 2025-01-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_alter_import_incoterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='package_type',
            field=models.CharField(choices=[('PALLET', 'Pallet'), ('BOX', 'Box'), ('KIT', 'Kit')], default='BOX', max_length=10),
        ),
        migrations.AlterField(
            model_name='import',
            name='incoterms',
            field=models.CharField(choices=[('NoN', 'NoN'), ('EXW', 'EXW – Ex Works'), ('FCA', 'FCA – Free Carrier'), ('CPT', 'CPT – Carriage Paid To'), ('CIP', 'CIP – Carriage and Insurance Paid To'), ('DAP', 'DAP – Delivered at Place'), ('DPU', 'DPU – Delivered at Place Unloaded'), ('DDP', 'DDP – Delivered Duty Paid')], default='NoN', max_length=3),
        ),
    ]
