# Generated by Django 5.1.5 on 2025-01-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_import_package_type_alter_import_incoterms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='import',
            name='height',
        ),
        migrations.RemoveField(
            model_name='import',
            name='length',
        ),
        migrations.RemoveField(
            model_name='import',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='import',
            name='width',
        ),
        migrations.AlterField(
            model_name='import',
            name='incoterms',
            field=models.CharField(choices=[('NoN', 'NoN'), ('EXW', 'EXW – Ex Works'), ('FCA', 'FCA – Free Carrier'), ('CPT', 'CPT – Carriage Paid To'), ('CIP', 'CIP – Carriage and Insurance Paid To'), ('DAP', 'DAP – Delivered at Place'), ('DPU', 'DPU – Delivered at Place Unloaded'), ('DDP', 'DDP – Delivered Duty Paid')], max_length=3),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('PALLET', 'PALLET'), ('BOX', 'BOX'), ('KIT', 'KIT')], max_length=20)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('gross_weight', models.FloatField()),
                ('import_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='imports.import')),
            ],
        ),
    ]
