# Generated by Django 5.1.5 on 2025-02-01 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_remove_import_gross_weight_remove_import_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='package_type',
            field=models.CharField(choices=[('PALLET', 'Pallet'), ('BOX', 'Box'), ('KIT', 'Kit')], default='PALLET', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('PALLET', 'Pallet'), ('BOX', 'Box'), ('KIT', 'Kit')], max_length=20),
        ),
        migrations.CreateModel(
            name='ImportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50)),
                ('line_number', models.IntegerField()),
                ('item_number', models.CharField(max_length=50)),
                ('description_eng', models.TextField()),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.FloatField()),
                ('line_cost', models.FloatField()),
                ('import_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_details', to='imports.import')),
            ],
        ),
    ]
