# Generated by Django 5.1.5 on 2025-02-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_import_package_type_alter_package_package_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='package_type',
        ),
    ]
