# Generated by Django 5.1.5 on 2025-02-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0007_remove_import_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Finished', 'Finished')], default='Active', max_length=10),
        ),
    ]
