# Generated by Django 5.1.5 on 2025-02-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_import_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='import',
            old_name='name',
            new_name='vendor_name',
        ),
    ]
