# Generated by Django 5.1.5 on 2025-02-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0009_rename_name_import_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('GEL', 'GEL - Georgian Lari')], default='USD', max_length=4),
        ),
    ]
