# Generated by Django 5.1.5 on 2025-02-02 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0010_import_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='description',
        ),
    ]
