# Generated by Django 5.1.5 on 2025-02-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0011_remove_import_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='forwarder_company',
            field=models.CharField(choices=[('Gebruder Weiss', 'Gebruder Weiss'), ('DBschenker', 'DBschenker'), ('DSV-Transglobe', 'DSV-Transglobe'), ('Gianti Logistics', 'Gianti Logistics'), ('FedEx', 'FedEx'), ('DHL', 'DHL'), ('UPS', 'UPS'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
