# Generated by Django 5.1.5 on 2025-02-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0012_import_forwarder_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='brokerage_invoice',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='import',
            name='commercial_invoice',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='import',
            name='declaration',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='import',
            name='other_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='import',
            name='transportation_invoice',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
