# Generated by Django 5.1.5 on 2025-02-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0013_import_brokerage_invoice_import_commercial_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='brokerage_invoice',
        ),
        migrations.RemoveField(
            model_name='import',
            name='commercial_invoice',
        ),
        migrations.RemoveField(
            model_name='import',
            name='declaration',
        ),
        migrations.RemoveField(
            model_name='import',
            name='other_document',
        ),
        migrations.RemoveField(
            model_name='import',
            name='transportation_invoice',
        ),
    ]
