# Generated by Django 5.1.5 on 2025-02-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0014_remove_import_brokerage_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
