# Generated by Django 5.1.5 on 2025-02-08 18:53

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0015_import_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
