# Generated by Django 5.1.5 on 2025-02-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0016_alter_import_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=50, unique=True)),
                ('description_eng', models.CharField(max_length=255)),
                ('description_geo', models.CharField(blank=True, max_length=255, null=True)),
                ('hs_code', models.CharField(blank=True, max_length=50, null=True)),
                ('net_weight', models.FloatField()),
            ],
        ),
    ]
