# Generated by Django 5.1.5 on 2025-02-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0017_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdetail',
            name='line_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
