# Generated by Django 5.1.5 on 2025-02-09 19:06

import imports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0018_alter_importdetail_line_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='brokerage_invoice',
            field=models.FileField(blank=True, null=True, upload_to=imports.models.upload_to),
        ),
        migrations.AddField(
            model_name='import',
            name='commercial_invoice',
            field=models.FileField(blank=True, null=True, upload_to=imports.models.upload_to),
        ),
        migrations.AddField(
            model_name='import',
            name='other_docs',
            field=models.FileField(blank=True, null=True, upload_to=imports.models.upload_to),
        ),
        migrations.AddField(
            model_name='import',
            name='transportation_invoice',
            field=models.FileField(blank=True, null=True, upload_to=imports.models.upload_to),
        ),
    ]
