# Generated by Django 5.1.5 on 2025-04-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0019_import_brokerage_invoice_import_commercial_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='brokerage_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='brokerage_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('GEL', 'GEL - Georgian Lari')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='other_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='other_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('GEL', 'GEL - Georgian Lari')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='transportation_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='transportation_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('GEL', 'GEL - Georgian Lari')], max_length=4, null=True),
        ),
    ]
