# Generated by Django 5.1.5 on 2025-04-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0020_import_brokerage_cost_import_brokerage_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Finished', 'Finished'), ('Delivered', 'Delivered')], default='Active', max_length=10),
        ),
    ]
