# Generated by Django 5.1.5 on 2025-04-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('main_user', 'Main User'), ('logistics', 'Logistics'), ('procurement', 'Procurement'), ('sales', 'Sales'), ('warehouse', 'Warehouse Employee')], default='main_user', max_length=20),
        ),
    ]
